AppProyecto1/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings
from AppProyecto2.views import contacto_exito, contacto

# Siempre utilizar app-proyecto1/ al final de http://127.0.0.1:8000/
# user: Esteban pass: Teclado97
# user: admin pass: 123
urlpatterns = [
    path('',inicio, name="Inicio"),
    path('tareas/',tareas, name="Tareas"),
    path('agregar-tarea/', agregar_tarea, name='agregar-tarea'),
    path('proyectos/',proyectos, name="Proyectos"),
    path('agregar-proyecto/',agregar_proyecto, name='agregar-proyecto'),
    path('miembros/',miembros, name="Miembros"), 
    path('agregar-miembro/', agregar_miembro, name='agregar-miembro'),
    path('buscar/',buscar, name='buscar'),
    path('about/',about, name="about"),
    path('tarea/<int:tarea_id>/', detalle_tarea, name='detalle_tarea'),
    path('proyecto/<int:proyecto_id>/', detalle_proyecto, name='detalle_proyecto'),
    path('miembro/<int:miembro_id>/', detalle_miembro, name='detalle_miembro'),
    path('login/',loginView, name="Login"),
    path('register/',register, name="Registrar"),
    path('logout/',LogoutView.as_view(template_name="logout.html"), name="Cerrar sesion"),
    path('editar-perfil/',editarPerfil, name="editarPerfil"),
    path('agregar-avatar/',agregarAvatar, name="agregar-avatar"),
    path('contacto/', contacto, name='contacto'),
    path('app-proyecto1/contacto-exito/', contacto_exito, name='contacto-exito'),
    ]
# AGREGAR LOS CAMPOS QUE AGREGAMOS A PROYECTO, A TODOS LOS MODELOS, HACER EL VIDEO, SUBIR LOS CASOS Y LISTO
# PROBAR SI LA WEB SIGUE FUNCIONANDO RETIRANDO LOS {{nuevoproyecto.as_p}} Y {{ nuevatarea.as_p }} EN AGREGAR PROYECTO Y TAREA.HTML

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include
from AppProyecto1.views import *
from django.conf import settings
from django.conf.urls.static import static
from AppProyecto2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app-proyecto1/', include ('AppProyecto1.urls')),
   
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppProyecto1/models.py
from django.db import models
from django.contrib.auth.models import User


class Miembro(models.Model):
    nombre = models.CharField(max_length=40, null=True)

    def __str__(self):
        return f'{self.nombre}'


class Proyecto(models.Model):
    nombredeproyecto = models.CharField(max_length=40)
    subtitulo = models.CharField(max_length=100, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    miembro = models.ForeignKey(Miembro, null=True, default=None, on_delete=models.CASCADE)
    fechaDeCreacion = models.DateField(null=True, blank=True)
    imagen = models.ImageField(upload_to='proyecto_imagenes/', null=True, blank=True)

    def __str__(self):
        return f'{self.nombredeproyecto} - {self.descripcion}'
    
    def tareas_asociadas(self):
        return Tarea.objects.filter(proyecto=self)


class Tarea(models.Model):
    ESTADO_CHOICES = (
        ('TO DO', 'To Do'),
        ('WIP', 'Work in Progress'),
        ('DONE', 'Done'),
    )

    nombredetarea = models.CharField(max_length=40)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES)
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nombredetarea} - {self.estado}'

    def __str__(self):
        return f'{self.nombredetarea} - {self.estado}'
    
    def proyectos_asociados(self):
        return Proyecto.objects.filter(tarea=self)

    
class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', blank=True, null=True)

AppProyecto1/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Avatar, Proyecto, Miembro


class TareaFormulario(forms.Form):
    ESTADO_CHOICES = (
        ('TO DO', 'To Do'),
        ('WIP', 'Work in Progress'),
        ('DONE', 'Done'),
    )

    nombredetarea = forms.CharField(max_length=40)
    estado = forms.ChoiceField(choices=ESTADO_CHOICES)
    proyecto = forms.ModelChoiceField(
        queryset=Proyecto.objects.all(),
        required=False,
        empty_label='Sin proyecto asociado'
    )


class ProyectoFormulario(forms.Form):

    nombredeproyecto = forms.CharField(max_length=40)
    subtitulo = forms.CharField(max_length=100, required=False)
    descripcion = forms.CharField(required=False, widget=forms.Textarea)
    fechaDeCreacion = forms.DateField(required=False)
    imagen = forms.ImageField(required=False)


class MiembroFormulario(forms.Form):

    nombre = forms.CharField(max_length=40)


class BusquedaFormulario(forms.Form):

    criterio = forms.CharField(max_length=100, required=True, label='Ingrese su criterio de búsqueda')

class UserEditForm(UserChangeForm):

    password = forms.CharField(
        help_text="",
        widget=forms.HiddenInput(), required=False
    )

    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model=User
        fields = ("email", "username", "password1", "password2")

    def clean_password2(self):

        print(self.cleaned_data)

        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden, por favor revise e intente nuevamente")
        return password2
    

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(help_text="")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class AvatarFormulario(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ("imagen",)

AppProyecto1/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def inicio(req):
    try:
        avatar = Avatar.objects.get(user=req.user.id)
        return render(req, "inicio.html", {"url_avatar": avatar.imagen.url})
    except:
        return render(req, "inicio.html")

@login_required(login_url='/app-proyecto1/login')
def tareas(req):
    try:
        avatar = Avatar.objects.get(user=req.user.id)
        return render (req, 'tareas.html', {"url_avatar": avatar.imagen.url})
    except:
        return render (req, 'tareas.html')

@login_required(login_url='/app-proyecto1/login')
def miembros(req):
    try:
        avatar = Avatar.objects.get(user=req.user.id)
        return render (req, 'miembros.html', {"url_avatar": avatar.imagen.url})
    except:
        return render (req, 'miembros.html')

@login_required(login_url='/app-proyecto1/login')
def proyectos(req):
    try:
        avatar = Avatar.objects.get(user=req.user.id)
        miembros = Miembro.objects.all()
        print(miembros)
        return render(req, 'proyectos.html', {"url_avatar": avatar.imagen.url, "miembros": miembros})
    except:
        return render(req, 'proyectos.html')

def about(req):
    try:
        avatar = Avatar.objects.get(user=req.user.id)
        return render (req, 'about.html', {"url_avatar": avatar.imagen.url})
    except:
        return render (req, 'about.html')

@login_required(login_url='/app-proyecto1/login')
def agregar_tarea(req):
    
    if req.method == 'POST':
        nuevatarea = TareaFormulario(req.POST)

        if nuevatarea.is_valid():
            data = nuevatarea.cleaned_data
            tarea = Tarea(
                nombredetarea=data["nombredetarea"],
                estado=data["estado"],
                proyecto=data.get("proyecto")
            )
            tarea.save()

            messages.success(req, 'Tarea agregada con éxito.')

            return render(req, 'tareas.html')
    else:
        nuevatarea = TareaFormulario()

    return render(req, 'agregar-tarea.html', {'nuevatarea': nuevatarea})

    
@login_required(login_url='/app-proyecto1/login')
def agregar_miembro(req):

     if req.method =='POST':
        nuevomiembro = MiembroFormulario(req.POST)

        if nuevomiembro.is_valid():
            data = nuevomiembro.cleaned_data
            miembro = Miembro(nombre=req.POST["nombre"]) 
            miembro.save()

            messages.success(req, 'Miembro agregado con éxito.')

            return render(req, 'miembros.html')
     else:
        nuevomiembro = MiembroFormulario()
    
     return render(req, 'agregar-miembro.html')

@login_required(login_url='/app-proyecto1/login')
def agregar_proyecto(req):

    if req.method == 'POST':
        nuevoproyecto = ProyectoFormulario(req.POST, req.FILES)

        if nuevoproyecto.is_valid():
            data = nuevoproyecto.cleaned_data

            miembro_id = req.POST.get("miembro")
            if miembro_id:
                try:
                    miembro = Miembro.objects.get(pk=miembro_id)
                except Miembro.DoesNotExist:
                    messages.error(req, 'El miembro seleccionado no existe.')
                    return render(req, 'agregar-proyecto.html', {"nuevoproyecto": nuevoproyecto})
            else:
                miembro = None

            proyecto = Proyecto(
                nombredeproyecto=data["nombredeproyecto"],
                subtitulo=data["subtitulo"],
                descripcion=data["descripcion"],
                miembro=miembro,
                fechaDeCreacion=data["fechaDeCreacion"],
                imagen=data["imagen"]
            ) 
            proyecto.save()

            messages.success(req, 'Proyecto agregado con éxito.')

            return render(req, 'proyectos.html', {"miembros": Miembro.objects.all()})
    else:
        nuevoproyecto = ProyectoFormulario()
    
    return render(req, 'agregar-proyecto.html')

@login_required(login_url='/app-proyecto1/login')
def buscar(req):
    tipo_busqueda = req.GET.get('tipo_busqueda')
    resultados = []

    try:
        avatar = Avatar.objects.get(user=req.user.id)

        if tipo_busqueda == 'tarea':
            resultados = Tarea.objects.all()
        elif tipo_busqueda == 'proyecto':
            resultados = Proyecto.objects.all()
        elif tipo_busqueda == 'miembro':
            resultados = Miembro.objects.all()
    except Avatar.DoesNotExist:
        avatar = None

    return render(req, 'buscar.html', {'tipo_busqueda': tipo_busqueda, 'resultados': resultados, 'url_avatar': avatar.imagen.url if avatar else None})


def detalle_tarea(req, tarea_id):
    tarea = get_object_or_404(Tarea, pk=tarea_id)
    return render(req, 'detalle_tarea.html', {'tarea': tarea})

def detalle_proyecto(req, proyecto_id):
    proyecto = get_object_or_404 (Proyecto, pk=proyecto_id)
    return render(req, 'detalle_proyecto.html', {'proyecto': proyecto})

def detalle_miembro (req, miembro_id):
    miembro = get_object_or_404 (Miembro, pk=miembro_id)
    return render(req, 'detalle_miembro.html', {'miembro': miembro})
 
def loginView(req):

    if req.method == 'POST':
        
        miFormulario = AuthenticationForm (req, data=req.POST)
        if miFormulario.is_valid():
            data = miFormulario.cleaned_data
            usuario = data ["username"]
            password = data ["password"]
            user = authenticate(username=usuario, password=password)

            if user:
                login(req, user)
                return render(req, "inicio.html", {"mensaje": f"Bienvendido {usuario}"})
            
        return render(req, "inicio.html", {"mensaje": f"Datos incorrectos, intente nuevamente"})
            
    else:
        miFormulario = AuthenticationForm()
        return render (req, "login.html", {"miFormulario": miFormulario})

def register(req):
    
    if req.method == 'POST':
        
        miFormulario = CustomUserCreationForm (req.POST)
        if miFormulario.is_valid():
            miFormulario.save()
            return render(req, "inicio.html", {"mensaje": f"Usuario {miFormulario.cleaned_data['username']} creado con éxito"})
                        
    else:
        miFormulario = CustomUserCreationForm()
        return render (req, "registro.html", {"miFormulario": miFormulario})

@login_required(login_url='/app-proyecto1/login')
def editarPerfil(req):
    
    usuario = req.user
    if req.method =='POST':

        miFormulario = UserEditForm(req.POST, instance=req.user)

        if miFormulario.is_valid():
            data = miFormulario.cleaned_data
            usuario.username = data["username"]
            usuario.password = data ["password"]
            usuario.email = data ["email"]
            usuario.set_password(data["password1"])
            usuario.save()

            return render (req, "editarPerfil.html", {"mensaje": "Datos correctamente actualizados"})
        else:
            return render (req, "editarPerfil.html", {"miFormulario": miFormulario})
 
    else:
        miFormulario = UserEditForm(instance=usuario)
        return render (req, "editarPerfil.html",{"miFormulario": miFormulario, "id": usuario.id})

    
def agregarAvatar(req):

    if req.method == 'POST':

        miFormulario = AvatarFormulario(req.POST, req.FILES)

        if miFormulario.is_valid():
            
            data = miFormulario.cleaned_data

            avatar = Avatar(user=req.user, imagen=data["imagen"])

            avatar.save()

            return render(req, "inicio.html", {"mensaje": "Avatar actualizado"})

    else:
        miFormulario = AvatarFormulario()
        return render(req, "agregar-avatar.html", {"miFormulario": miFormulario})
  
    

AppProyecto1/templates/agregar-avatar.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

<form action="{% url 'agregar-avatar' %}" enctype="multipart/form-data" method="post">{% csrf_token %}

    {{miFormulario.as_p}}

    <button type="submit"> Agregar </button>
</form>

{% endblock ContendoQueCambia %}

AppProyecto1/templates/agregar-proyecto.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

    <h3>Agregar nuevo proyecto</h3>

    <form method="POST" action="{% url 'agregar-proyecto' %}">
        {% csrf_token %}

            
        <div class="form-group">
            <label for="{{ nuevoproyecto.nombredeproyecto.id_for_label }}">Nombre del Proyecto:</label>
            {{ nuevoproyecto.nombredeproyecto }}
        </div>
    
        <div class="form-group">
            <label for="{{ nuevoproyecto.subtitulo.id_for_label }}">Subtítulo:</label>
            {{ nuevoproyecto.subtitulo }}
        </div>
    
        <div class="form-group">
            <label for="{{ nuevoproyecto.descripcion.id_for_label }}">Descripción:</label>
            {{ nuevoproyecto.descripcion }}
        </div>
    
        <div class="form-group">
            <label for="{{ nuevoproyecto.miembro.id_for_label }}">Miembro:</label>
            {{ nuevoproyecto.miembro }}
        </div>
    
        <div class="form-group">
            <label for="{{ nuevoproyecto.fechaDeCreacion.id_for_label }}">Fecha de Creación:</label>
            {{ nuevoproyecto.fechaDeCreacion }}
        </div>
    
        <div class="form-group">
            <label for="{{ nuevoproyecto.imagen.id_for_label }}">Imagen:</label>
            {{ nuevoproyecto.imagen }}
        </div>
    
        <button type="submit">Guardar</button>
    </form>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/agregar-tarea.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

<h3>Agregar nueva tarea</h3>

<form method="POST" action="{% url 'agregar-tarea' %}">
    {% csrf_token %}
    
    
    <div class="form-group">
        <label for="{{ nuevatarea.nombredetarea.id_for_label }}">Nombre de la Tarea:</label>
        {{ nuevatarea.nombredetarea }}
    </div>
    
    <div class="form-group">
        <label for="{{ nuevatarea.estado.id_for_label }}">Estado:</label>
        {{ nuevatarea.estado }}
    </div>
    
    <div class="form-group">
        <label for="{{ nuevatarea.proyecto.id_for_label }}">Proyecto:</label>
        {{ nuevatarea.proyecto }}
    </div>
    
    <button type="submit">Guardar Tarea</button>
</form>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/buscar.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}
    <h1>Buscar</h1>

    <form method="get" action="{% url 'buscar' %}">
        <h3>Buscar tareas</h3>
        <button type="submit" name="tipo_busqueda" value="tarea">Buscar tareas</button>
    </form>
    
    {% if tipo_busqueda == 'tarea' %}
        <h3>Resultados de búsqueda de tareas:</h3>
        <ul>
            {% for tarea in resultados %}
                <li>
                    {{ tarea.nombredetarea }}
                    <a href="{% url 'detalle_tarea' tarea.id %}" class="btn btn-primary btn-sm">Leer más</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="get" action="{% url 'buscar' %}">
        <h3>Buscar proyectos</h3>
        <button type="submit" name="tipo_busqueda" value="proyecto">Buscar proyectos</button>
    </form>

    {% if tipo_busqueda == 'proyecto' %}
        <h3>Resultados de búsqueda de proyectos:</h3>
        <ul>
            {% for proyecto in resultados %}
                <li>
                    {{ proyecto.nombredeproyecto }}
                    <a href="{% url 'detalle_proyecto' proyecto.id %}" class="btn btn-primary btn-sm">Leer más</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="get" action="{% url 'buscar' %}">
        <h3>Buscar miembros</h3>
        <button type="submit" name="tipo_busqueda" value="miembro">Buscar miembros</button>
    </form>

    {% if tipo_busqueda == 'miembro' %}
        <h3>Resultados de búsqueda de miembros:</h3>
        <ul>
            {% for miembro in resultados %}
                <li>
                    {{ miembro.nombre }}
                    <a href="{% url 'detalle_miembro' miembro.id %}" class="btn btn-primary btn-sm">Leer más</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    
</form>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/detalle_miembro.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

<h1>Detalles del Miembro</h1>
<p><strong>Nombre del Miembro:</strong> {{ miembro.nombre }}</p>
<p><strong>Tareas asignadas:</strong></p>

<ul>
    {% for tarea in miembro.tarea_set.all %}
        <li>{{ tarea.nombredetarea }}</li>
    {% endfor %}
</ul>

<a href="{% url 'buscar' %}" class="btn btn-primary btn-sm">Atrás</a>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/detalle_tarea.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

<h1>Detalles de la Tarea</h1>
    <p><strong>Nombre de la Tarea:</strong> {{ tarea.nombredetarea }}</p>
    <p><strong>Estado:</strong> {{ tarea.estado }}</p>
    <p><strong>Proyecto al que pertenece la tarea:</strong> {{ tarea.proyecto.nombredeproyecto }}</p>
    <p><strong>Miembro asignado a la tarea:</strong> {{ tarea.miembro.nombre }}</p>

    <a href="{% url 'buscar' %}" class="btn btn-primary btn-sm">Atrás</a>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/editarPerfil.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}
<h1>Editar perfil</h1>

    <div class="text-center">
      <img height="40px" src="{{url_avatar}}">
    </div>

<form action="{% url 'editarPerfil' %}" method="POST">{% csrf_token %}

    {{ miFormulario.as_p}}

  <button type="submit"> Editar </button>

</form>

<a href="{% url 'agregar-avatar' %}" class="btn btn-primary">Agregar o cambiar avatar</a>


{% endblock ContendoQueCambia %}

AppProyecto1/templates/footer.html
 <!-- Footer-->
 <footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item"><a href="/app-proyecto1/about">Acerca de mi</a></li>
                    <li class="list-inline-item"><a href="{% url 'contacto' %}">Contáctanos</a></li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0"></p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item me-4">
                        <a href="https://www.linkedin.com/in/esteban-napolitano/" target="_blank"><i class="bi-linkedin fs-3"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

AppProyecto1/templates/inicio.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}
    <h1>Bienvenido! {{usuario}}</h1>
    <p>Estos son mis primeros pasos en el desarrollo web con Django</p>
{% endblock ContendoQueCambia %}

AppProyecto1/templates/login.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}
<form action ="{% url 'Login' %}" method="POST" action="">
    {% csrf_token %}

    {{miFormulario.as_p}}
        
    <button type="submit">Ingresar</button>

</form>

{% endblock ContendoQueCambia %}

AppProyecto1/templates/logout.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

<h1>Sesión cerrada, hasta luego!</h1>

<a href="{% url 'Inicio' %}">Inicio</a>

{% endblock ContendoQueCambia %}

AppProyecto1/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'navbar.html' %}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Mi primera web</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

    
        {% block ContendoQueCambia %}
            
        {% endblock ContendoQueCambia %}
        
        {% include 'footer.html' %} 
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppProyecto1/templates/registro.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}
<form action ="{% url 'Registrar' %}" method="POST">
    {% csrf_token %}

    {{miFormulario.as_p}}
    
    <button type="submit">Registrarse</button>

</form>

{% endblock ContendoQueCambia %}

AppProyecto1/templates/tareas.html
{% extends 'padre.html' %}

{% block ContendoQueCambia %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

<h1>Vista de Tareas</h1>
<h3>Agregar nueva tarea</h3>
<form method="POST" action="{% url 'agregar-tarea' %}">
    {% csrf_token %}
    
    <p>Nombre de la Tarea: <input type="text" name="nombredetarea" required></p>
    
    <p>Estado:
        <select name="estado" required>
            <option value="TO DO">To Do</option>
            <option value="WIP">Work in Progress</option>
            <option value="DONE">Done</option>
        </select>
    </p>
    
    <p>Proyecto:
        <select name="proyecto">
            <option value="" selected>Sin proyecto asociado</option>
            {% for proyecto in proyectos %}
                <option value="{{ proyecto.id }}">{{ proyecto.nombredeproyecto }}</option>
            {% endfor %}
        </select>
    </p>
    
    <button type="submit">Guardar Tarea</button>
    
</form>

<ul>
    {% for tarea in tareas %}
        <li>{{ tarea.nombredetarea }} - {{ tarea.estado }} - Proyecto: {{ tarea.proyecto }}</li>
    {% endfor %}
</ul>

{% endblock ContendoQueCambia %}